services:

  filegator:
    image: filegator/filegator:latest
    container_name: filegator
    restart: unless-stopped
    ports:
      - "8282:8080"  # O el Puerto de preferencia 
    volumes:
      - ./configuration.php:/var/www/filegator/configuration.php:rw
      - repository:/var/www/filegator/repository
      - private:/var/www/filegator/private

volumes:
  repository:
  private:
